### ISSUE TITLE
Document borders during training?

### ISSUE THREAD

**Issue by stephenroller** [ryankiros/skip-thoughts#1]
Hi Ryan,

Your paper was a very nice read. One question I'm unclear on after reading the paper and skimming the code: did you respect document boundaries in your training objective? It looks like you just concatenated all your documents together, meaning the last sentence of one document will need to predict the first sentence of the next. While you use very large documents (books), I could see this confounding things using resources with many smaller documents, like Wikipedia.

Just asking for clarification.

Thanks,
Stephen

**Comment by ryankiros** [comment]
Hi Stephen,

That's correct. We figured this was negligible in the case of books. 

For smaller documents, you're right that this might become a concern. A possible way to respect document boundaries given the current code would be to: pass a list of lists to the trainer function (one list for each document), call HomogeneousData on each document, then add an extra for-loop in the training code. I haven't tried this myself, though this or some variant of it should do the job.

Ryan
