### ISSUE TITLE
TypeError during training

### ISSUE THREAD

**Issue by tractorist** [ryankiros/skip-thoughts#2]
Hi Ryan,

I tried to start training a new model from scratch following you instructions but soon after I execute the command:
train.trainer(X)
I get following error:
TypeError: ('An update must have the same type as the original shared variable (shared_var=<TensorType(float32, matrix)>, shared_var.type=TensorType(float32, matrix), update_val=Elemwise{add,no_inplace}.0, update_val.type=TensorType(float64, matrix)).', 'If the difference is related to the broadcast pattern, you can call the tensor.unbroadcast(var, axis_to_unbroadcast[, ...]) function to remove broadcastable dimensions.')

Don't have any ideas what I am doing wrong. Do you have any suggestions?

Artem

**Comment by ryankiros** [comment]
Hi Artem,

Try adding floatX=float32 to your Theano flags.

**Comment by tractorist** [comment]
Thanks, that helped! And thanks for sharing the code.
