### ISSUE TITLE
building a custom decoder

### ISSUE THREAD

**Issue by jtoy** [ryankiros/skip-thoughts#25]
I'm trying to train a custom decoder. I am using the bookcorpus data with science fiction novels.  According to the docs:
https://github.com/ryankiros/skip-thoughts/blob/master/decoding/README.md

"We assume that you have two lists of strings available: X which are the target sentences and C which are the source sentences. "

what exactly is X and C with these books? I see the bookcorpus data are just text files.   I'm not sure what kind of processing im supposed to do here to get them in the right format for training.

**Comment by ncoronges** [comment]
It looks like X is explained explicitly in the trainer README but I cannot figure out what C is either (the "source sentences.")  In trainer README author writes 

> Suppose that you have a list of strings available for training, where the contents of the entries are contiguous (so the (i+1)th entry is the sentence that follows the i-th entry. As an example, you can download our BookCorpus dataset, which was used for training the models available on the main page. Lets call this list X. Note that each string should already be tokenized (so that split() will return the desired tokens).

Any help on C appreciated @ryankiros .

**Comment by junfenglx** [comment]
My thought is:
From decoding perspective, you should have two sentence as inputs,
one is the conditioned sentence, the other is decoder input sentence,
and another sentence as target(decoder output sentence).

For example, Translation problem(English -> French):
X is a French sentence(target sentence),
C is a English sentence(the conditioned source sentence, also as decoder input sentence)
C is used twice.

**Comment by ncoronges** [comment]
thank you for your response @junfenglx. In the romance novel scenario which this project [refers to,](https://github.com/ryankiros/neural-storyteller) what do you see the target  and source being?

**Comment by giddyyupp** [comment]
hi,
i believe for the neuralstoryteller project, X should be the romance novels, C should be Coco captions, and model is skipthoughts. but i am not sure. i am currently training my own decoder with this configuration, if it works fine then i ll let you know.

**Comment by danielricks** [comment]
If anyone else is having trouble creating a decoder, I've written simplified code to do that here: https://github.com/danielricks/penseur
