### ISSUE TITLE
train.trainer returns error

### ISSUE THREAD

**Issue by iamtrask** [ryankiros/skip-thoughts#3]
TypeError: ('An update must have the same type as the original shared variable (shared_var=<TensorType(float32, matrix)>, shared_var.type=TensorType(float32, matrix), update_val=Elemwise{add,no_inplace}.0, update_val.type=TensorType(float64, matrix)).', 'If the difference is related to the broadcast pattern, you can call the tensor.unbroadcast(var, axis_to_unbroadcast[, ...]) function to remove broadcastable dimensions.')

**Comment by iamtrask** [comment]
i've gone through the tutorial a couple of times, can't seem to figure out what's not working

**Comment by ryankiros** [comment]
https://github.com/ryankiros/skip-thoughts/issues/2

I'll add a note about this on the main page.

**Comment by iamtrask** [comment]
Thanks for getting back so fast!

**Comment by iamtrask** [comment]
This fixed the issue as well. Feel free to close.
