### ISSUE TITLE
Download Error:Connection reset by peer

### ISSUE THREAD

**Issue by lilhope** [ryankiros/skip-thoughts#36]
I follow the guide in ReadMe.md to download the dictionary.txt file. It works well in the begin,but when progress bar reach to 31%,it throws an error:`connection reset by peer.`I can download the other 6 files,such as uni_skip.npz,bi_skip.npz.pkl...Could you help me to download this file or provide an avilable download link? Thanks in advance!

**Comment by danielricks** [comment]
Here's a link to that file, if you still need it:
https://drive.google.com/open?id=0B3lpCS07rg43ZDJoQ3kzZHRRRTQ

**Comment by lilhope** [comment]
@danielricks Thanks！
