### ISSUE TITLE
How to train the Bi-skip model mentioned in the paper?

### ISSUE THREAD

**Issue by bdhingra** [ryankiros/skip-thoughts#4]
Hello Ryan,

Thanks a lot for the excellent code. I was trying to train the Bi-skip model mentioned in your paper on my dataset. However only the uni-skip model seems to be present in the training code. Is that correct? Do you plan to add it?

Thanks in advance!
Bhuwan

**Comment by ryankiros** [comment]
Hi Bhuwan,

That's correct. Sure, I can add this but it might take some time (super busy at the moment)

In the mean time, you could use this as a guide if you want to modify the training code yourself:
https://github.com/ryankiros/skip-thoughts/blob/master/skipthoughts.py#L302-L322

Ryan

**Comment by bdhingra** [comment]
Thank you Ryan. That seems pretty straightforward.
