### ISSUE TITLE
Could not convert string to float:Unpickling error

### ISSUE THREAD

**Issue by Avhirup** [ryankiros/skip-thoughts#40]
![capture](https://cloud.githubusercontent.com/assets/12384502/22965604/52b5fa7e-f384-11e6-8179-cabea57435fe.PNG)
 I have the same .pkl files as mentioned in the readme .

**Comment by zhangju0220** [comment]
I have the same problems with you，have you ever deal with this problem?

**Comment by navneetkrc** [comment]
Hi Avhirup,
How did you solved this issue?
