### ISSUE TITLE
can't download those embedding and model files

### ISSUE THREAD

**Issue by jdxyw** [ryankiros/skip-thoughts#73]
can't download those embedding and model files

**Comment by SumanyuShukla** [comment]
Facing the same problem today, yesterday it was working fine.

**Comment by jdxyw** [comment]
It seems that the site http://www.cs.toronto.edu is down. Any other place to download it?

**Comment by SumanyuShukla** [comment]
Not that I know of.

**Comment by jdxyw** [comment]
the site is back now.
